name: Rustfmt Check

on:
  push:
    branches:
      - 'next'
    paths:
      - '.github/workflows/rustfmt.yml'
      - 'userspace/ksud_magic/**'
      - 'userspace/ksud_overlayfs/**'
  pull_request:
    branches:
      - 'next'
    paths:
      - '.github/workflows/rustfmt.yml'
      - 'userspace/ksud_magic/**'
      - 'userspace/ksud_overlayfs/**'

permissions:
  checks: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Rustfmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Rustfmt Check on ksud_magic
        uses: LoliGothick/rustfmt-check@master
        with:
          token: ${{ github.token }}
          working-directory: userspace/ksud_magic

      - name: Rustfmt Check on ksud_overlayfs
        uses: LoliGothick/rustfmt-check@master
        with:
          token: ${{ github.token }}
          working-directory: userspace/ksud_overlayfs
